#!/bin/sh

if which lighttpd >/dev/null 2>&1; then
  lighttpd=lighttpd
else
  lighttpd=/usr/sbin/lighttpd
fi

conffile=$(mktemp)
document_root=$(cd $(dirname $0)/.. && pwd)/public
port=1234

cat > $conffile <<-EOF
server.document-root = "$document_root"
server.port = $port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
dir-listing.encoding        = "utf-8"
server.dir-listing          = "enable"
index-file.names            = ( "index.html" )
EOF

cleanup() {
  rm -f "$conffile"
}
trap cleanup INT QUIT

echo "I: Go to: http://localhost:$port/"
echo "I: Hit Control+C to stop"
echo "or"
echo "open public/index.html in your browser." 
echo
$lighttpd -f "$conffile" -D
